export const cards = [
  {
    name: 'Mark Henry',
    cardNumber: '2020 2020 2020 2020',
    expirationDate: '12/25',
    cvc: '123',
    freezed: false,
    transactions: [
      {
        date: "2 Mar 2024",
        amount: 414.05,
        transactionType: "refund",
        paymentType: "card",
        description: "Grocery store purchase",
        type: "fileStorage",
      },
      {
        date: "19 Sep 2024",
        amount: 196.87,
        transactionType: "withdrawal",
        paymentType: "cash",
        description: "Restaurant charge",
        type: "flight",
      },
      {
        date: "1 Feb 2024",
        amount: 139.16,
        transactionType: "transfer",
        paymentType: "card",
        description: "Gift card purchase",
        type: "megaPhone"
      },
      {
        date: "9 Jan 2021",
        amount: 176.38,
        transactionType: "purchase",
        paymentType: "bank",
        description: "Grocery store purchase",
        type: "megaPhone"
      },
      {
        date: "27 Mar 2024",
        amount: 51.26,
        transactionType: "transfer",
        paymentType: "card",
        description: "Gas station",
        type: "flight",
      },
      {
        date: "22 May 2024",
        amount: 79.25,
        transactionType: "refund",
        paymentType: "bank",
        description: "Grocery store purchase",
        type: "fileStorage",
      },
      {
        date: "5 Apr 2022",
        amount: 497.84,
        transactionType: "transfer",
        paymentType: "bank",
        description: "Gas station",
        type: "megaPhone",
      },
      {
        date: "3 Sep 2020",
        amount: 22.45,
        transactionType: "refund",
        paymentType: "bank",
        description: "Restaurant charge",
        type: "fileStorage",
      }
    ],
  },
  {
    name: 'Samantha Rivers',
    cardNumber: '4111 1111 1111 1111',
    expirationDate: '11/27',
    cvc: '456',
    freezed: true,
    transactions: [
      {
        date: "27 Oct 2022",
        amount: 246.71,
        transactionType: "transfer",
        paymentType: "cash",
        description: "Online shopping",
        type: "fileStorage",
      },
      {
        date: "7 Nov 2023",
        amount: 362.26,
        transactionType: "transfer",
        paymentType: "bank",
        description: "Restaurant charge",
        type: "flight",
      },
      {
        date: "21 Nov 2022",
        amount: 482.63,
        transactionType: "refund",
        paymentType: "card",
        description: "Refund from retailer",
        type: "megaPhone",
      },
      {
        date: "3 Mar 2021",
        amount: 201.27,
        transactionType: "purchase",
        paymentType: "bank",
        description: "Utility bill payment",
        type: "fileStorage",
      },
      {
        date: "1 Jun 2020",
        amount: 223.65,
        transactionType: "withdrawal",
        paymentType: "cash",
        description: "Grocery store purchase",
        type: "flight",
      },
      {
        date: "10 Oct 2024",
        amount: 76.83,
        transactionType: "purchase",
        paymentType: "refund",
        description: "Utility bill payment",
        type: "fileStorage",
      },
      {
        date: "25 Mar 2022",
        amount: 390.17,
        transactionType: "refund",
        paymentType: "cash",
        description: "Gift card purchase",
        type: "flight",
      },
      {
        date: "19 Jun 2022",
        amount: 496,
        transactionType: "transfer",
        paymentType: "card",
        description: "Gas station",
        type: "megaPhone",
      },
      {
        date: "24 Nov 2021",
        amount: 364.25,
        transactionType: "purchase",
        paymentType: "card",
        description: "Gift card purchase",
        type: "fileStorage",
      }
    ],
  },
  {
    name: 'Derek Zhao',
    cardNumber: '5500 0000 0000 0004',
    expirationDate: '06/26',
    cvc: '789',
    freezed: false,
    transactions: [
      {
        date: "4 Oct 2021",
        amount: 202.59,
        transactionType: "transfer",
        paymentType: "bank",
        description: "Restaurant charge",
        type: "flight",
      },
      {
        date: "20 Sep 2023",
        amount: 383.56,
        transactionType: "transfer",
        paymentType: "cash",
        description: "Gift card purchase",
        type: "fileStorage",
      },
      {
        date: "28 Dec 2023",
        amount: 161.21,
        transactionType: "purchase",
        paymentType: "bank",
        description: "ATM withdrawal",
        type: "flight",
      },
      {
        date: "16 Jul 2020",
        amount: 253.41,
        transactionType: "withdrawal",
        paymentType: "cash",
        description: "Restaurant charge",
        type: "fileStorage",
      },
      {
        date: "25 Dec 2023",
        amount: 124.93,
        transactionType: "refund",
        paymentType: "bank",
        description: "Money transfer",
        type: "megaPhone",
      }
    ],
  },
  {
    name: 'Lucia Delgado',
    cardNumber: '3400 0000 0000 009',
    expirationDate: '03/29',
    cvc: '321',
    freezed: false,
    transactions: [
      {
        date: "19 Nov 2024",
        amount: 23.95,
        transactionType: "transfer",
        paymentType: "card",
        description: "Utility bill payment",
        type: "megaPhone",
      },
      {
        date: "3 Jul 2023",
        amount: 218.48,
        transactionType: "transfer",
        paymentType: "bank",
        description: "Utility bill payment",
        type: "fileStorage",
      },
      {
        date: "20 Mar 2024",
        amount: 442.02,
        transactionType: "withdrawal",
        paymentType: "card",
        description: "Online shopping",
        type: "flight",
      },
      {
        date: "12 Aug 2022",
        amount: 50.16,
        transactionType: "transfer",
        paymentType: "refund",
        description: "Money transfer",
        type: "flight",
      },
    ],
  },
  {
    name: 'Tariq Ahmad',
    cardNumber: '6011 0000 0000 0004',
    expirationDate: '10/28',
    cvc: '852',
    freezed: true,
    transactions: [
      {
        date: "21 Oct 2024",
        amount: 485.86,
        transactionType: "withdrawal",
        paymentType: "cash",
        description: "Gift card purchase",
        type: "megaPhone",
      },
      {
        date: "27 Jan 2024",
        amount: 98.19,
        transactionType: "purchase",
        paymentType: "refund",
        description: "Money transfer",
        type: "fileStorage",
      },
      {
        date: "7 Aug 2024",
        amount: 143.96,
        transactionType: "withdrawal",
        paymentType: "bank",
        description: "Utility bill payment",
        type: "flight",
      },
      {
        date: "17 Jun 2020",
        amount: 102.63,
        transactionType: "refund",
        paymentType: "bank",
        description: "Refund from retailer",
        type: "flight",
      },
      {
        date: "13 Oct 2021",
        amount: 288.28,
        transactionType: "withdrawal",
        paymentType: "cash",
        description: "Online shopping",
        type: "megaPhone",
      }
    ],
  },
  {
    name: 'Natalie Kim',
    cardNumber: '3000 0000 0004',
    expirationDate: '07/30',
    cvc: '963',
    freezed: false,
    transactions: [
      {
        date: "18 Jul 2024",
        amount: 396.05,
        transactionType: "refund",
        paymentType: "cash",
        description: "App subscription",
        type: "megaPhone",
      },
      {
        date: "19 Feb 2020",
        amount: 200.34,
        transactionType: "refund",
        paymentType: "card",
        description: "ATM withdrawal",
        type: "fileStorage",
      },
      {
        date: "23 Feb 2020",
        amount: 392.29,
        transactionType: "transfer",
        paymentType: "card",
        description: "Gas station",
        type: "flight",
      },
      {
        date: "3 Aug 2022",
        amount: 21.29,
        transactionType: "transfer",
        paymentType: "bank",
        description: "Gas station",
        type: "fileStorage",
      },
      {
        date: "18 Dec 2021",
        amount: 406.25,
        transactionType: "refund",
        paymentType: "card",
        description: "App subscription",
        type: "flight",
      }
    ],
  },
]